const acronyms = [
    { ac: "AED", desc: "Automatic Entity Deletion", link: "http://some-link-to-confluence" },
    { ac: "AOB", desc: "Any Other Business", link: "http://some-link-to-confluence" },
    { ac: "ATS", desc: "Automatic Translation System", link: "http://some-link-to-confluence" },
    { ac: "BAU", desc: "Business As Usual", link: "http://some-link-to-confluence" },
    { ac: "BE", desc: "Back-End", link: "http://some-link-to-confluence" },
    { ac: "BLSA", desc: "Bin Location Stock Awareness", link: "http://some-link-to-confluence" },
    { ac: "BOM", desc: "Bill of Material", link: "http://some-link-to-confluence" },
    { ac: "BRD", desc: "Business requirements document", link: "http://some-link-to-confluence" },
    { ac: "C.N.", desc: "Credit Note", link: "http://some-link-to-confluence" },
    { ac: "CAS", desc: "Courier Aggregation System", link: "http://some-link-to-confluence" },
    { ac: "CDO", desc: "Cached Delivery Option", link: "http://some-link-to-confluence" },
    { ac: "CFS", desc: "Collect From Showroom", link: "http://some-link-to-confluence" },
    { ac: "CIC", desc: "Concurrent Invoice and Collect", link: "http://some-link-to-confluence" },
    { ac: "CSM", desc: "Cloud SQL Migration", link: "http://some-link-to-confluence" },
    { ac: "CNV", desc: "Credit Note Validation", link: "http://some-link-to-confluence" },
    { ac: "CR", desc: "Change Request", link: "http://some-link-to-confluence" },
    { ac: "CTA", desc: "Call to action", link: "http://some-link-to-confluence" },
    { ac: "DD", desc: "Delivery Date", link: "http://some-link-to-confluence" },
    { ac: "DDC", desc: "Delivery Date Change", link: "http://some-link-to-confluence" },
    { ac: "DDCD", desc: "Delivery Date Change Detection", link: "http://some-link-to-confluence" },
    { ac: "DDCN", desc: "Delivery Date Change Notification", link: "http://some-link-to-confluence" },
    { ac: "DDSE", desc: "Delivery Date Service Expectation", link: "http://some-link-to-confluence" },
    { ac: "DOW", desc: "Day Of Week", link: "http://some-link-to-confluence" },
    { ac: "DSD", desc: "Denormalised Sales Data", link: "http://some-link-to-confluence" },
    { ac: "DSS", desc: "Digital Software Sales", link: "http://some-link-to-confluence" },
    { ac: "DTE", desc: "Downstream Service", link: "http://some-link-to-confluence" },
    { ac: "EDQ", desc: "Event Driven Queue", link: "http://some-link-to-confluence" },
    { ac: "EFT", desc: "Electronic Funds Transfer", link: "http://some-link-to-confluence" },
    { ac: "EOL", desc: "End of Life", link: "http://some-link-to-confluence" },
    { ac: "FAII", desc: "Full Amazon Inventory Integration", link: "http://some-link-to-confluence" },
    { ac: "FE", desc: "Front-End", link: "http://some-link-to-confluence" },
    { ac: "FOMO", desc: "Fear Of Missing Out", link: "http://some-link-to-confluence" },
    { ac: "GP", desc: "Global Payments", link: "http://some-link-to-confluence" },
    { ac: "GRN", desc: "Goods Received Note", link: "http://some-link-to-confluence" },
    { ac: "I&C", desc: "Invoice and collect", link: "http://some-link-to-confluence" },
    { ac: "LEGACY I&C", desc: "Invoice and collect DSS", link: "http://some-link-to-confluence" },
    { ac: "ICPAPI", desc: "Invoice and collect process API", link: "http://some-link-to-confluence" },
    { ac: "IDDPP", desc: "Inventory Delivery Date Prediction Process", link: "http://some-link-to-confluence" },
    { ac: "IHTO", desc: "Inter-Hub Transfer Order", link: "http://some-link-to-confluence" },
    { ac: "ISR", desc: "Internal Shipping Request", link: "http://some-link-to-confluence" },
    { ac: "JP", desc: "JudoPay", link: "http://some-link-to-confluence" },
    { ac: "LHAS", desc: "Local Hub Administration System", link: "http://some-link-to-confluence" },
    { ac: "LHSP", desc: "Local Hub Stock Profile", link: "http://some-link-to-confluence" },
    { ac: "MATT", desc: "Monitor All The Things", link: "http://some-link-to-confluence" },
    { ac: "MATT DAEMON", desc: "Monitor All The Things Daemon", link: "http://some-link-to-confluence" },
    { ac: "ME", desc: "Manage Environment ", link: "http://some-link-to-confluence" },
    { ac: "MoM", desc: "Meeting of Meetings", link: "http://some-link-to-confluence" },
    { ac: "MSR", desc: "Minimum Stock Recommendation", link: "http://some-link-to-confluence" },
    { ac: "MT1", desc: "Megatron", link: "http://some-link-to-confluence" },
    { ac: "MVP", desc: "Minimum Viable Product", link: "http://some-link-to-confluence" },
    { ac: "NRT", desc: "Near Real Time update for Google", link: "http://some-link-to-confluence" },
    { ac: "OHQM", desc: "On Hand Quantity Management", link: "http://some-link-to-confluence" },
    { ac: "OLDF", desc: "Order Level Duty Fees", link: "http://some-link-to-confluence" },
    { ac: "OOH", desc: "Out Of Hours", link: "http://some-link-to-confluence" },
    { ac: "OoO", desc: "Out of Office", link: "http://some-link-to-confluence" },
    { ac: "OOS", desc: "Out of Stock", link: "http://some-link-to-confluence" },
    { ac: "PA", desc: "Part Allocation", link: "http://some-link-to-confluence" },
    { ac: "PDP", desc: "Product description Page", link: "http://some-link-to-confluence" },
    { ac: "PID", desc: "Project Inititation Document", link: "http://some-link-to-confluence" },
    { ac: "PILS", desc: "Product Index Listing Service", link: "http://some-link-to-confluence" },
    { ac: "PLP", desc: "Product Listing Page", link: "http://some-link-to-confluence" },
    { ac: "PO", desc: "Purchase Order", link: "http://some-link-to-confluence" },
    { ac: "POL", desc: "Purchase Order Line", link: "http://some-link-to-confluence" },
    { ac: "POW", desc: "Purchase Order Workflow", link: "http://some-link-to-confluence" },
    { ac: "PR", desc: "Pull Request", link: "http://some-link-to-confluence" },
    { ac: "PRDB", desc: "Product Relationship Data Base", link: "http://some-link-to-confluence" },
    { ac: "PRS", desc: "Product Recommendation System", link: "http://some-link-to-confluence" },
    { ac: "PSQ", desc: "Profile Stock Quantity", link: "http://some-link-to-confluence" },
    { ac: "PSV", desc: "Profile Stock Value", link: "http://some-link-to-confluence" },
    { ac: "PUB", desc: "PickUp DropOff (PUDO) Points", link: "http://some-link-to-confluence" },
    { ac: "RCL", desc: "Returns Centre Live", link: "http://some-link-to-confluence" },
    { ac: "RFC", desc: "Request For Comments", link: "http://some-link-to-confluence" },
    { ac: "RMP", desc: "Re-Marketing Platform", link: "http://some-link-to-confluence" },
    { ac: "RRP", desc: "Recommended Retail Price", link: "http://some-link-to-confluence" },
    { ac: "RAGD", desc: "Recursive acronym Glossary Document", link: "http://some-link-to-confluence" },
    { ac: "SC", desc: "Service Category", link: "http://some-link-to-confluence" },
    { ac: "SCA", desc: "Service Category Availability", link: "http://some-link-to-confluence" },
    { ac: "SDS", desc: "Supplier Drop Shipping", link: "http://some-link-to-confluence" },
    { ac: "SEF URL", desc: "Search Engine Friendly URL", link: "http://some-link-to-confluence" },
    { ac: "SKU", desc: "Stock Keeping Unit", link: "http://some-link-to-confluence" },
    { ac: "SLT", desc: "Standard Lead Time", link: "http://some-link-to-confluence" },
    { ac: "SME", desc: "Subject Matter Expert", link: "http://some-link-to-confluence" },
    { ac: "SNAFU", desc: "situation normal all fouled up", link: "http://some-link-to-confluence" },
    { ac: "SPA", desc: "Single Page Application", link: "http://some-link-to-confluence" },
    { ac: "Spike", desc: "investigatory estimates / work", link: "http://some-link-to-confluence" },
    { ac: "ST4M", desc: "SprintTools for Megatron", link: "http://some-link-to-confluence" },
    { ac: "SV", desc: "SKU Variation", link: "http://some-link-to-confluence" },
    { ac: "SVG", desc: "SKU Variation Group", link: "http://some-link-to-confluence" },
    { ac: "TDAC", desc: "Technical Debt and Change", link: "http://some-link-to-confluence" },
    { ac: "UAT", desc: "User acceptance Testing", link: "http://some-link-to-confluence" },
    { ac: "URN", desc: "Unique Reference Number", link: "http://some-link-to-confluence" },
    { ac: "WEEE", desc: "Waste electrical and electronic equipment", link: "http://some-link-to-confluence" },
    { ac: "WMS", desc: "Website Megatron Shared", link: "http://some-link-to-confluence" },
    { ac: "WPN", desc: "Web Page Node", link: "http://some-link-to-confluence" },
    { ac: "STLG", desc: "Senior Team Leadship Group", link: "http://some-link-to-confluence" }
]

module.exports = { acronyms }